server:
  port: 8083

spring:
  application:
    name: payment-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/paymentdb
    username: postgres
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000
payment:
  vnpay:
    url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    tmnCode: DQ2QRKII
    secretKey: FSK6DMH5TQ03QHP03H2YUHBHCA1HHIH5
    returnUrl: http://localhost:3000/home/cart
    orderType: billpayment
    ipvnUrl: http://localhost:8080/api/v1/payments/vnpay-callback

eureka:
  client:
    register-with-eureka: true  # Đăng ký service này với Eureka
    fetch-registry: true  # Lấy danh sách các service từ Eureka
    service-url:
      defaultZone: http://localhost:8761/eureka/

momo:
  partner-code: MOMOLRJZ20181206
  access-key: mTCKt9W3eU1m39TW
  secret-key: SetA5RDnLHvt51AULf51DyauxUo3kDU6
  endpoint: https://test-payment.momo.vn/v1/gateway/api