server:
  port: 8083

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: vuquochuy.01012003@gmail.com
    password: ${PASSWORD_EMAIL}
    properties:
        mail.smtp:
            auth: true
            starttls.enable: true
            ssl.trust: smtp.gmail.com


  application:
    name: payment-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres?sslmode=require
    username: postgres.nonefnlmplqixtnymooo
    password: ${PASSWORD_DB}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: redis-12494.c340.ap-northeast-2-1.ec2.redns.redis-cloud.com
      port: 12494
      timeout: 60000
      password: ${PASSWORD_REDIS}
      ssl:
        enabled: true
payment:
  vnpay:
    url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    tmnCode: ${TMA_CODE}
    secretKey: ${SECRET_KEY}
    returnUrl: http://localhost:3000/home/cart
    orderType: billpayment
    ipvnUrl: https://gatewayservice-e9hh.onrender.com/api/v1/payments/vnpay-callback

eureka:
  client:
    register-with-eureka: true  # Đăng ký service này với Eureka
    fetch-registry: true  # Lấy danh sách các service từ Eureka
    service-url:
      defaultZone: https://eurekaserver-ksbs.onrender.com/eureka/
