server:
  port: 8085

spring:
  application:
    name: user-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://dpg-d1druc3e5dus73dtfj6g-a:5432/userdb_aqub
    username: admin
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
  data:
    redis:
      host: redis-17597.c340.ap-northeast-2-1.ec2.redns.redis-cloud.com
      port: 17597
      password: ${PASSWORD_REDIS}
      timeout: 60000
      ssl:
        enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            redirect-uri: http://localhost:3000/auth/google-callback
            scope:
              - email
              - profile
jwt:
  token:
    validity: 86400000
  secretKey: ${JWT_SECRET_KEY}
  expiration: 9000000
  header: Authorization
  prefix: Bearer
  refresh-token:
    expiration: 604800000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL}